### ISSUE TITLE
Allow basic auth only option without configuration file for Python SDK configuration and login

### ISSUE THREAD

**Issue by tlpensando** [pensando/psm-tools#81]
Currently, the constructor for the configuration.py in the Python SDK requires a configuration file to be present such as ~/.psm/config.json.  Enhancement request to eliminate the requirement for this and accept basic auth only such that automation tools, etc. do not require this file to be present.

**Comment by jsilberm** [comment]
Closed with https://github.com/pensando/psm-tools/pull/82
