### ISSUE TITLE
Module: 'requests' missing in requirement.txt file for package 'pensando-dss' when tested with Python 3.6.8

### ISSUE THREAD

**Issue by guptaankit23** [pensando/psm-tools#93]
**Describe the bug**
Documentation Bug:
To seamlessly import python package 'pensando-dss' in any automation script, it was found that the module 'requests' needs to be installed first which is not mentioned in requirement.txt file.

**To Reproduce**
Steps Used:

Environment: Python 3.6.8

Required Python Modules:
Below modules also needs to be installed along with ‘pip install pensando-dss’ before importing ‘pensando_dss’ module out of which 'requests' is not mentioned in requirement.txt file.

- Urllib3
- Requests
- dateutil

Installed pensando-dss:
[root@Taormina-PSM ~]# python3 -m pip install pensando-dss
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting pensando-dss

  Downloading https://files.pythonhosted.org/packages/90/1e/e8b576a424769f82436593a850eeed45c1322b22dacb9bb0ae8837a58548/pensando_dss-1.29.0rc1-py3-none-any.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 910kB/s 
Collecting nulltype (from pensando-dss)
  Downloading https://files.pythonhosted.org/packages/00/0f/47dde1a3cceac9858da0bfb92d2279bf5f993ed075b72983e92efc297db3/nulltype-2.3.1-py2.py3-none-any.whl
Installing collected packages: nulltype, pensando-dss
Successfully installed nulltype-2.3.1 pensando-dss-1.29.0rc1
[root@Taormina-PSM ~]# 

Import failed for missing 'urllib3' module:
[root@Taormina-PSM ~]# python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import pensando_dss.psm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pensando_dss/__init__.py", line 1, in <module>
    from pensando_dss.psm import *
  File "/usr/local/lib/python3.6/site-packages/pensando_dss/psm/__init__.py", line 16, in <module>
    from pensando_dss.psm.api_client import ApiClient
  File "/usr/local/lib/python3.6/site-packages/pensando_dss/psm/api_client.py", line 21, in <module>
    from urllib3.fields import RequestField
ModuleNotFoundError: No module named 'urllib3'
>>> 
>>> 
[root@Taormina-PSM ~]# 
[root@Taormina-PSM ~]# python3 -m pip install urllib3
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting urllib3
  Downloading https://files.pythonhosted.org/packages/4e/b8/f5a25b22e803f0578e668daa33ba3701bb37858ec80e08a150bd7d2cf1b1/urllib3-1.26.8-py2.py3-none-any.whl (138kB)
    100% |████████████████████████████████| 143kB 7.6MB/s 
Installing collected packages: urllib3
Successfully installed urllib3-1.26.8
[root@Taormina-PSM ~]# 

Import failed for missing 'requests' module:
[root@Taormina-PSM ~]# python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import pensando_dss.psm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pensando_dss/__init__.py", line 1, in <module>
    from pensando_dss.psm import *
  File "/usr/local/lib/python3.6/site-packages/pensando_dss/psm/__init__.py", line 16, in <module>
    from pensando_dss.psm.api_client import ApiClient
  File "/usr/local/lib/python3.6/site-packages/pensando_dss/psm/api_client.py", line 25, in <module>
    from pensando_dss.psm.configuration import Configuration
  File "/usr/local/lib/python3.6/site-packages/pensando_dss/psm/configuration.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
>>> 
>>> 
[root@Taormina-PSM ~]# 
[root@Taormina-PSM ~]# python3 -m pip install requests
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting requests
  Downloading https://files.pythonhosted.org/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 5.2MB/s 
Collecting certifi>=2017.4.17 (from requests)
  Downloading https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl (149kB)
    100% |████████████████████████████████| 153kB 6.5MB/s 
Collecting charset-normalizer~=2.0.0; python_version >= "3" (from requests)
  Downloading https://files.pythonhosted.org/packages/84/3e/1037abe6498e65d645ce7a22d3402605d49a3b2c7f20c3abb027760da4f0/charset_normalizer-2.0.10-py3-none-any.whl
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests)
Collecting idna<4,>=2.5; python_version >= "3" (from requests)
  Downloading https://files.pythonhosted.org/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl (61kB)
    100% |████████████████████████████████| 61kB 14.5MB/s 
Installing collected packages: certifi, charset-normalizer, idna, requests
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.10 idna-3.3 requests-2.27.1
[root@Taormina-PSM ~]# 

Import failed for missing 'dateutil' module:
[root@Taormina-PSM ~]# python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pensando_dss.psm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pensando_dss/__init__.py", line 1, in <module>
    from pensando_dss.psm import *
  File "/usr/local/lib/python3.6/site-packages/pensando_dss/psm/__init__.py", line 16, in <module>
    from pensando_dss.psm.api_client import ApiClient
  File "/usr/local/lib/python3.6/site-packages/pensando_dss/psm/api_client.py", line 27, in <module>
    from pensando_dss.psm.model_utils import (
  File "/usr/local/lib/python3.6/site-packages/pensando_dss/psm/model_utils.py", line 19, in <module>
    from dateutil.parser import parse
ModuleNotFoundError: No module named 'dateutil'
>>> 
>>> 
[root@Taormina-PSM ~]# 
[root@Taormina-PSM ~]# 
[root@Taormina-PSM ~]# python3 -m pip install python-dateutil
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting python-dateutil
  Downloading https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (247kB)
    100% |████████████████████████████████| 256kB 5.5MB/s 
Collecting six>=1.5 (from python-dateutil)
  Downloading https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil
Successfully installed python-dateutil-2.8.2 six-1.16.0
[root@Taormina-PSM ~]# 

Worked after installing all above modules:
[root@Taormina-PSM ~]# python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pensando_dss.psm
>>> 

**Expected behavior**
Module 'requests' to be added in requirement.txt file

**Screenshots**

**Environment (please complete the following information):**
 - python version: 3.6.8
 - PSM version: 1.29.1-T-5

**Comment by jsilberm** [comment]
This has been addressed in https://github.com/pensando/psm-tools/pull/94
